os: osx

branches:
  only:
  - blog

language: node_js

node_js:
- stable

before_install:
- git config --global user.name "luck9star"
- git config --global user.email hadyenvip@gmail.com
- brew install nasm

install:
- npm install hexo-cli -g
- npm install hexo --save
- npm install hexo-deployer-git --save
- npm install

script:
- hexo clean
- hexo generate
# - hexo d
after_script:
- sed -i "s/github_token/${GITHUB_TOKEN}/g" ./_config.yml
- sed -i "s/coding_token/${CODING_TOKEN}/g" ./_config.yml
- hexo d
